# -*- coding: utf-8 -*-
"""GenerativeAI0005.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7XYYd_PLH5A7vReY1pJC1PMyolbrwEk
"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-classification")
pipe("Today is a beautiful day")

pipe("Today is such a dull day raining and water logged all around the city")

summarizer = pipeline("summarization")

ARTICLE = """ URI, Indian-administered Kashmir — The night of May 8 returns to Sanam Bashir as a jumble of disjointed images. Her family was packed into three cars. The road was so dark, she said, and the artillery fire deafening.

“It felt like the night of judgment,” said Bashir, 20, who was huddled in the back seat with her little cousin, 4-year-old Muheeb, her aunt and her mother, Nargis Begum.

Bashir doesn’t remember the shrapnel striking the roof of the car, but she can’t forget her aunt’s sharp cry, or the hot blood that poured from her mother’s neck. Begum was dead by the time they reached the hospital.

At least 27 people were killed, including 11-year old twins, and more than 50 injured in the Indian-administered territory of Jammu and Kashmir over four days of fighting between India and Pakistan. The sudden violence was the worst to hit the contested region in decades and, as in previous rounds of conflict, civilians bore the heaviest cost.

Days into a fragile ceasefire, The Washington Post visited villages less than 10 miles from the Line of Control — the de facto border that snakes over mountains and across rivers, carving Kashmir in two.

Years of relative calm were shattered last month when militants gunned down 26 civilians near the popular tourist town of Pahalgam, in Indian-administered Kashmir. New Delhi said the attack had links to Pakistan, which it has long accused of supporting violent separatists. Islamabad denied any involvement. The region held its breath."""

summarizer(ARTICLE)

from diffusers import AutoPipelineForText2Image
import torch

pipeline = AutoPipelineForText2Image.from_pretrained("stable-diffusion-v1-5/stable-diffusion-v1-5", torch_dtype=torch.float16, variant="fp16").to("cuda")

image = pipeline("Brahmos missile hits Pakistan").images[0]
image.save("GenAISPC.png")  # Saves as PNG in the current directory

image

image0 = pipeline("Mars surface and spaceship seen floating, humanoids space miners extracting rare earth minerals").images[0]

image0

from transformers import pipeline
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")
text = "We are learning a few lines of code in Gen AI."
labels = ["travel", "cooking", "technology"]

result = classifier(text, labels)
print(result)

from transformers import pipeline
classifier = pipeline("text-classification", model="distilbert-base-uncased-finetuned-sst-2-english")
text = "We are learning a new lines of code in Gen AI"
result = classifier(text)
print(result)

from diffusers import AutoPipelineForText2Image
import torch

pipeline = AutoPipelineForText2Image.from_pretrained("stable-diffusion-v1-5/stable-diffusion-v1-5", torch_dtype=torch.float16, variant="fp16").to("cuda")
image0 = pipeline("Street flood water is sucked by robot giant sucker made of thick rubber").images[0]

image0

image0 = pipeline("Robots underground sucking all surface waters and discharging it using pipelines").images[0]

image0